# Generated by Django 4.1.2 on 2022-10-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='offices',
            field=models.ManyToManyField(to='main.office'),
        ),
    ]
