# Generated by Django 4.1.2 on 2022-12-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_timelog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timelog",
            name="time_in",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
